name: Publish Python Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure this is correctly set in your repo secrets

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Get the current version from setup.py
      id: get_version
      run: |
        version=$(python setup.py --version)
        echo "::set-output name=version::$version"

    - name: Set up Git credentials
      run: |
        git config user.name "${{ secrets.GIT_USER_NAME }}"
        git config user.email "${{ secrets.GIT_USER_EMAIL }}"
        git remote set-url origin https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Debug Remote URL
      run: echo "Remote URL: https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

    - name: Verify Remote Access
      run: git ls-remote https://x-access-token:${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Create Git Tag
      run: |
        git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"
        git push origin v${{ steps.get_version.outputs.version }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        body: |
          This release contains the latest version of the package.
        draft: false
        prerelease: false
